"use client";

import { useEffect, useState } from "react";
import { Loader2 } from "lucide-react";
import { useUsernameStore } from "@/components/Providers/contextProvider"; // Zustand store
import MarkdownFade from "./ui/markdownFade";
import { ImprovementSuggestionProps } from "@/app/types";
import SleepingCat from "./cat";


export function ImprovementSuggestion({
  userData,
  problemStats,
}: ImprovementSuggestionProps) {
  const { username } = useUsernameStore() as { username: string };
  const [suggestion, setSuggestion] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [currentUsername, setCurrentUsername] = useState<string>(username);

  // Clear suggestion and update currentUsername when username changes
  useEffect(() => {
    setSuggestion(null);
    setCurrentUsername(username);
  }, [username]);

  const getSuggestion = async () => {
    // Verify that the current username matches the one in the store
    // This prevents using old data with a new username
    if (currentUsername !== username) {
      console.log("Username changed, cancelling suggestion request");
      return;
    }

    setIsLoading(true);
    try {
      const response = await fetch("/api/getsuggestion", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          userData: { ...userData, handle: username }, // Ensure correct username is used
          problemStats,
        }),
      });
      // fetch only rejects on a network failure, so a 500 or a 503 arrives here
      // as a perfectly good JSON body with no `suggestion` in it — which used to
      // set undefined and silently put the idle button back.
      const data = await response.json().catch(() => null);

      // Check again before setting state to avoid race conditions
      if (currentUsername === username) {
        const failed = !response.ok || !data?.suggestion;
        if (failed) void fetch("/api/metric", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ name: "coach:failed" }),
        }).catch(() => {});
        setSuggestion(
          failed
            ? "Sorry, we couldn't generate a suggestion at this time. Please try again later."
            : data.suggestion
        );
      }
    } catch (error) {
      console.error("Error fetching suggestion:", error);
      if (currentUsername === username) {
        setSuggestion(
          "Sorry, we couldn't generate a suggestion at this time. Please try again later."
        );
      }
    } finally {
      if (currentUsername === username) {
        setIsLoading(false);
      }
    }
  };

  const action =
    "border border-rule px-3.5 py-2.5 text-meta text-muted-foreground transition-colors hover:bg-rowhover hover:text-foreground disabled:opacity-40";

  return (
    <div className="relative border-b border-rule">
      <div className="flex min-h-[44px] items-center justify-between gap-4 border-b border-hair px-5 py-2.5">
        <span className="text-meta font-medium text-muted-foreground">
          What to work on next
        </span>
        <span className="shrink-0 text-label text-faint">generated by Gemini</span>
      </div>

      <div className="px-5 pb-6 pt-4">
        {suggestion ? (
          <>
            <MarkdownFade
              content={suggestion}
              className="mb-4 max-w-[900px] text-body leading-[1.7] text-muted-foreground"
            />
            <button type="button" className={action} onClick={() => setSuggestion(null)}>
              Ask again
            </button>
          </>
        ) : (
          <button
            type="button"
            className={action}
            onClick={getSuggestion}
            disabled={isLoading}
          >
            {isLoading ? (
              <>
                <Loader2 className="mr-2 inline h-3.5 w-3.5 animate-spin" />
                Generating…
              </>
            ) : (
              "Get a personalized suggestion"
            )}
          </button>
        )}
        {!suggestion && !isLoading && (
          <div className="absolute -bottom-1 right-10 z-10">
            <SleepingCat />
          </div>
        )}
      </div>
    </div>
  );
}